### PR TITLE
ROUTING-1234: adding support for new rtiserviceadmincpp library in Fi…

### PR DESCRIPTION
**Pull request by juanlu-rti**
Fixes ROUTING-1234.

### Proposed changes

Add CMake variables and rules to make the new `rtiserviceadmincpp` library available for examples.

### CODE REVIEW

**Review by fgaranda — APPROVED** [review]

**Comment by juanlu-rti** [comment]
@fgaranda , @lulivi , do you think we should merge this into a different branch? This new library, `rtiserviceadmincpp` is only going to be available, for the moment, in JH-F1. Will builds fail without that library being present?

**Comment by lulivi** [comment]
> @fgaranda , @lulivi , do you think we should merge this into a different branch? This new library, `rtiserviceadmincpp` is only going to be available, for the moment, in JH-F1. Will builds fail without that library being present?

When using this code and the new modified code in https://github.com/rticommunity/rticonnextdds-examples/pull/697 with an old version of Connext (E.g.: 7.3.0) you will get:

```
> cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release && cmake --build .
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
...
-- RTI Connext installation directory: /home/luis/ndds/rti_connext_dds-7.3.0
-- RTI Connext architecture: x64Linux4gcc7.3.0
-- Found RTIConnextDDS: /home/luis/ndds/rti_connext_dds-7.3.0 (found suitable version "7.3.0.0", minimum required is "7.0.0") found components:  core routing_service recording_service 
-- Generating done
...
[ 75%] Building CXX object CMakeFiles/ServiceAsLibExample.dir/ServiceAsLibExample.cxx.o
gmake[2]: *** No rule to make target 'librtiserviceadmincpp_release_shared-NOTFOUND', needed by 'ServiceAsLibExample'.  Stop.
gmake[2]: Leaving directory '/home/luis/r/comm/lulivi-rticonnextdds-examples/examples/recording_service/service_as_lib/c++11/build'
gmake[1]: *** [CMakeFiles/Makefile2:74: CMakeFiles/ServiceAsLibExample.dir/all] Error 2
gmake[1]: Leaving directory '/home/luis/r/comm/lulivi-rticonnextdds-examples/examples/recording_service/service_as_lib/c++11/build'
gmake: *** [Makefile:84: all] Error 2
```

Which is expected.

If the imported target is not requested (e.g.: old verision of the recording service as a library example) you will get:

```
> cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release && cmake --build .
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
...
-- RTI Connext installation directory: /home/luis/ndds/rti_connext_dds-7.3.0
-- RTI Connext architecture: x64Linux4gcc7.3.0
-- Found RTIConnextDDS: /home/luis/ndds/rti_connext_dds-7.3.0 (found suitable version "7.3.0.0", minimum required is "7.0.0") found components:  core routing_service recording_service 
-- Generating done
...
[ 75%] Building CXX object CMakeFiles/ServiceAsLibExample.dir/ServiceAsLibExample.cxx.o
[100%] Linking CXX executable ServiceAsLibExample
gmake[2]: Leaving directory '/home/luis/r/comm/lulivi-rticonnextdds-examples/examples/recording_service/service_as_lib/c++11/build'
[100%] Built target ServiceAsLibExample
gmake[1]: Leaving directory '/home/luis/r/comm/lulivi-rticonnextdds-examples/examples/recording_service/service_as_lib/c++11/build'
```

**Comment by juanlu-rti** [comment]
@lulivi , do you think this is ready to be merged?

**Comment by lulivi** [comment]
@juanlu-rti since I wasn't able to test it on Windows, let's wait until we have the necessary packages to do it. Then we will merge if everything is correct.

**Comment by lulivi** [comment]
Works fine on windows too:

```
C:\Users\TEMP.RTIDOMAIN.000\rticonnextdds-examples\examples\recording_service\service_as_lib\c++11\build>cmake .. -DBUILD_SHARED_LIBS=ON -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release
...
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- RTI Connext installation directory: C:/Users/TEMP.RTIDOMAIN.000/rti_connext_dds-7.4.0
-- RTI Connext architecture: x64Win64VS2017
-- Found RTIConnextDDS: C:/Users/TEMP.RTIDOMAIN.000/rti_connext_dds-7.4.0 (found suitable version "7.4.0.0", minimum required is "6.1.0") found components:  core
-- RTI Connext installation directory: C:/Users/TEMP.RTIDOMAIN.000/rti_connext_dds-7.4.0
-- RTI Connext architecture: x64Win64VS2017
-- Found RTIConnextDDS: C:/Users/TEMP.RTIDOMAIN.000/rti_connext_dds-7.4.0 (found suitable version "7.4.0.0", minimum required is "7.0.0") found components:  core routing_service recording_service
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/TEMP.RTIDOMAIN.000/rticonnextdds-examples/examples/recording_service/service_as_lib/c++11/build

C:\Users\TEMP.RTIDOMAIN.000\rticonnextdds-examples\examples\recording_service\service_as_lib\c++11\build>cmake --build . --config Release
...
Done Building Project "C:\Users\TEMP.RTIDOMAIN.000\rticonnextdds-examples\examples\recording_service\service_as_lib\c++11\build\ZERO_CHECK.vcxproj" (default targets).
Done Building Project "C:\Users\TEMP.RTIDOMAIN.000\rticonnextdds-examples\examples\recording_service\service_as_lib\c++11\build\ServiceAsLibC++11_RecorderXml_qos.vcxproj" (default targets).
Done Building Project "C:\Users\TEMP.RTIDOMAIN.000\rticonnextdds-examples\examples\recording_service\service_as_lib\c++11\build\ServiceAsLibC++11_ReplayXml_qos.vcxproj" (default targets).
Done Building Project "C:\Users\TEMP.RTIDOMAIN.000\rticonnextdds-examples\examples\recording_service\service_as_lib\c++11\build\ServiceAsLibExample.vcxproj" (default targets).
Done Building Project "C:\Users\TEMP.RTIDOMAIN.000\rticonnextdds-examples\examples\recording_service\service_as_lib\c++11\build\ALL_BUILD.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:19.96
```

**Review by lulivi — APPROVED** [review]

**Pull request merged**
